# Generated by Django 4.2.16 on 2024-11-13 06:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_audiofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('object_person', django.db.models.manager.Manager()),
            ],
        ),
    ]
